# Hazelbean

Hazelbean is a collection of geospatial processing tools based on gdal, numpy, scipy, cython, pygeoprocessing, taskgraph, natcap.invest, geopandas and many others to assist in common spatial analysis tasks in sustainability science, ecosystem service assessment, global integrated modelling assessment, natural capital accounting, and/or calculable general equilibrium modelling.

Note that for all of the features of hazelbean to work, your computer will need to be configured to compile Cython files to C code. This workflow is tested in a Python 3.10, 64 bit Windows environment. It should work on other system environments, but this is not yet tested.

## Installation

Follow the instructions in the Earth-Economy Devstack repository.

## Quickstart

Test that hazelbean imports correctly. Importing it will trigger compilation of the C files if they are not there.

``` python
import hazelbean as hb
```

From here, explore examples of the useful spatial, statistical and economic functions in the examples section of this documentation. A good starting example would be the `zonal_statistics` function. These functions are documented in their code declarations and in the Hazelbean Spatial Algorithms section. #TODOO[Make Link]. Anothr good starting point would be to understand the `ProjectFlow()` object, which is described in the project_flow page #TODOO[make link]



